// Generated by gencpp from file all_msgs_srvs/bdinfomsg.msg
// DO NOT EDIT!


#ifndef ALL_MSGS_SRVS_MESSAGE_BDINFOMSG_H
#define ALL_MSGS_SRVS_MESSAGE_BDINFOMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace all_msgs_srvs
{
template <class ContainerAllocator>
struct bdinfomsg_
{
  typedef bdinfomsg_<ContainerAllocator> Type;

  bdinfomsg_()
    : node_name()
    , device_id(0)
    , isNew(0)
    , timenow()
    , lon(0.0)
    , alt(0.0)  {
    }
  bdinfomsg_(const ContainerAllocator& _alloc)
    : node_name(_alloc)
    , device_id(0)
    , isNew(0)
    , timenow(_alloc)
    , lon(0.0)
    , alt(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _node_name_type;
  _node_name_type node_name;

   typedef int32_t _device_id_type;
  _device_id_type device_id;

   typedef int32_t _isNew_type;
  _isNew_type isNew;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _timenow_type;
  _timenow_type timenow;

   typedef float _lon_type;
  _lon_type lon;

   typedef float _alt_type;
  _alt_type alt;





  typedef boost::shared_ptr< ::all_msgs_srvs::bdinfomsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::all_msgs_srvs::bdinfomsg_<ContainerAllocator> const> ConstPtr;

}; // struct bdinfomsg_

typedef ::all_msgs_srvs::bdinfomsg_<std::allocator<void> > bdinfomsg;

typedef boost::shared_ptr< ::all_msgs_srvs::bdinfomsg > bdinfomsgPtr;
typedef boost::shared_ptr< ::all_msgs_srvs::bdinfomsg const> bdinfomsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::all_msgs_srvs::bdinfomsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::all_msgs_srvs::bdinfomsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::all_msgs_srvs::bdinfomsg_<ContainerAllocator1> & lhs, const ::all_msgs_srvs::bdinfomsg_<ContainerAllocator2> & rhs)
{
  return lhs.node_name == rhs.node_name &&
    lhs.device_id == rhs.device_id &&
    lhs.isNew == rhs.isNew &&
    lhs.timenow == rhs.timenow &&
    lhs.lon == rhs.lon &&
    lhs.alt == rhs.alt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::all_msgs_srvs::bdinfomsg_<ContainerAllocator1> & lhs, const ::all_msgs_srvs::bdinfomsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace all_msgs_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs_srvs::bdinfomsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs_srvs::bdinfomsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs_srvs::bdinfomsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs_srvs::bdinfomsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs_srvs::bdinfomsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs_srvs::bdinfomsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::all_msgs_srvs::bdinfomsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8bc75b840511959862d72a0c796ab46a";
  }

  static const char* value(const ::all_msgs_srvs::bdinfomsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8bc75b8405119598ULL;
  static const uint64_t static_value2 = 0x62d72a0c796ab46aULL;
};

template<class ContainerAllocator>
struct DataType< ::all_msgs_srvs::bdinfomsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "all_msgs_srvs/bdinfomsg";
  }

  static const char* value(const ::all_msgs_srvs::bdinfomsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::all_msgs_srvs::bdinfomsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string node_name\n"
"int32 device_id\n"
"int32 isNew\n"
"string timenow\n"
"float32 lon\n"
"float32 alt\n"
;
  }

  static const char* value(const ::all_msgs_srvs::bdinfomsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::all_msgs_srvs::bdinfomsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.node_name);
      stream.next(m.device_id);
      stream.next(m.isNew);
      stream.next(m.timenow);
      stream.next(m.lon);
      stream.next(m.alt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bdinfomsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::all_msgs_srvs::bdinfomsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::all_msgs_srvs::bdinfomsg_<ContainerAllocator>& v)
  {
    s << indent << "node_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.node_name);
    s << indent << "device_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.device_id);
    s << indent << "isNew: ";
    Printer<int32_t>::stream(s, indent + "  ", v.isNew);
    s << indent << "timenow: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.timenow);
    s << indent << "lon: ";
    Printer<float>::stream(s, indent + "  ", v.lon);
    s << indent << "alt: ";
    Printer<float>::stream(s, indent + "  ", v.alt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALL_MSGS_SRVS_MESSAGE_BDINFOMSG_H
