// Generated by gencpp from file all_msgs_srvs/settingcallback.msg
// DO NOT EDIT!


#ifndef ALL_MSGS_SRVS_MESSAGE_SETTINGCALLBACK_H
#define ALL_MSGS_SRVS_MESSAGE_SETTINGCALLBACK_H

#include <ros/service_traits.h>


#include <all_msgs_srvs/settingcallbackRequest.h>
#include <all_msgs_srvs/settingcallbackResponse.h>


namespace all_msgs_srvs
{

struct settingcallback
{

typedef settingcallbackRequest Request;
typedef settingcallbackResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct settingcallback
} // namespace all_msgs_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::all_msgs_srvs::settingcallback > {
  static const char* value()
  {
    return "a893383d462b2192990ef4619919d478";
  }

  static const char* value(const ::all_msgs_srvs::settingcallback&) { return value(); }
};

template<>
struct DataType< ::all_msgs_srvs::settingcallback > {
  static const char* value()
  {
    return "all_msgs_srvs/settingcallback";
  }

  static const char* value(const ::all_msgs_srvs::settingcallback&) { return value(); }
};


// service_traits::MD5Sum< ::all_msgs_srvs::settingcallbackRequest> should match
// service_traits::MD5Sum< ::all_msgs_srvs::settingcallback >
template<>
struct MD5Sum< ::all_msgs_srvs::settingcallbackRequest>
{
  static const char* value()
  {
    return MD5Sum< ::all_msgs_srvs::settingcallback >::value();
  }
  static const char* value(const ::all_msgs_srvs::settingcallbackRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::all_msgs_srvs::settingcallbackRequest> should match
// service_traits::DataType< ::all_msgs_srvs::settingcallback >
template<>
struct DataType< ::all_msgs_srvs::settingcallbackRequest>
{
  static const char* value()
  {
    return DataType< ::all_msgs_srvs::settingcallback >::value();
  }
  static const char* value(const ::all_msgs_srvs::settingcallbackRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::all_msgs_srvs::settingcallbackResponse> should match
// service_traits::MD5Sum< ::all_msgs_srvs::settingcallback >
template<>
struct MD5Sum< ::all_msgs_srvs::settingcallbackResponse>
{
  static const char* value()
  {
    return MD5Sum< ::all_msgs_srvs::settingcallback >::value();
  }
  static const char* value(const ::all_msgs_srvs::settingcallbackResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::all_msgs_srvs::settingcallbackResponse> should match
// service_traits::DataType< ::all_msgs_srvs::settingcallback >
template<>
struct DataType< ::all_msgs_srvs::settingcallbackResponse>
{
  static const char* value()
  {
    return DataType< ::all_msgs_srvs::settingcallback >::value();
  }
  static const char* value(const ::all_msgs_srvs::settingcallbackResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ALL_MSGS_SRVS_MESSAGE_SETTINGCALLBACK_H
