// Generated by gencpp from file all_msgs_srvs/settingcallbackRequest.msg
// DO NOT EDIT!


#ifndef ALL_MSGS_SRVS_MESSAGE_SETTINGCALLBACKREQUEST_H
#define ALL_MSGS_SRVS_MESSAGE_SETTINGCALLBACKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace all_msgs_srvs
{
template <class ContainerAllocator>
struct settingcallbackRequest_
{
  typedef settingcallbackRequest_<ContainerAllocator> Type;

  settingcallbackRequest_()
    : fram_id(0)
    , type(0)
    , data()  {
    }
  settingcallbackRequest_(const ContainerAllocator& _alloc)
    : fram_id(0)
    , type(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _fram_id_type;
  _fram_id_type fram_id;

   typedef uint32_t _type_type;
  _type_type type;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator> const> ConstPtr;

}; // struct settingcallbackRequest_

typedef ::all_msgs_srvs::settingcallbackRequest_<std::allocator<void> > settingcallbackRequest;

typedef boost::shared_ptr< ::all_msgs_srvs::settingcallbackRequest > settingcallbackRequestPtr;
typedef boost::shared_ptr< ::all_msgs_srvs::settingcallbackRequest const> settingcallbackRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator1> & lhs, const ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator2> & rhs)
{
  return lhs.fram_id == rhs.fram_id &&
    lhs.type == rhs.type &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator1> & lhs, const ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace all_msgs_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5c7050b588d4aced7c3d6a605ad2ff0";
  }

  static const char* value(const ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5c7050b588d4aceULL;
  static const uint64_t static_value2 = 0xd7c3d6a605ad2ff0ULL;
};

template<class ContainerAllocator>
struct DataType< ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "all_msgs_srvs/settingcallbackRequest";
  }

  static const char* value(const ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 fram_id\n"
"uint32 type\n"
"float32[] data\n"
;
  }

  static const char* value(const ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fram_id);
      stream.next(m.type);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct settingcallbackRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::all_msgs_srvs::settingcallbackRequest_<ContainerAllocator>& v)
  {
    s << indent << "fram_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.fram_id);
    s << indent << "type: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.type);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALL_MSGS_SRVS_MESSAGE_SETTINGCALLBACKREQUEST_H
