// Generated by gencpp from file all_msgs_srvs/systemState.msg
// DO NOT EDIT!


#ifndef ALL_MSGS_SRVS_MESSAGE_SYSTEMSTATE_H
#define ALL_MSGS_SRVS_MESSAGE_SYSTEMSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace all_msgs_srvs
{
template <class ContainerAllocator>
struct systemState_
{
  typedef systemState_<ContainerAllocator> Type;

  systemState_()
    : device_id(0)
    , temperature(0.0)
    , occ_RAM(0.0)
    , occ_CPU(0.0)
    , occ_GPU(0.0)
    , occ_memory_sda1(0.0)
    , occ_memory_home(0.0)
    , precess_state(0.0)
    , camera_state(0.0)
    , mmlidar_state(0.0)  {
    }
  systemState_(const ContainerAllocator& _alloc)
    : device_id(0)
    , temperature(0.0)
    , occ_RAM(0.0)
    , occ_CPU(0.0)
    , occ_GPU(0.0)
    , occ_memory_sda1(0.0)
    , occ_memory_home(0.0)
    , precess_state(0.0)
    , camera_state(0.0)
    , mmlidar_state(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _device_id_type;
  _device_id_type device_id;

   typedef float _temperature_type;
  _temperature_type temperature;

   typedef float _occ_RAM_type;
  _occ_RAM_type occ_RAM;

   typedef float _occ_CPU_type;
  _occ_CPU_type occ_CPU;

   typedef float _occ_GPU_type;
  _occ_GPU_type occ_GPU;

   typedef float _occ_memory_sda1_type;
  _occ_memory_sda1_type occ_memory_sda1;

   typedef float _occ_memory_home_type;
  _occ_memory_home_type occ_memory_home;

   typedef float _precess_state_type;
  _precess_state_type precess_state;

   typedef float _camera_state_type;
  _camera_state_type camera_state;

   typedef float _mmlidar_state_type;
  _mmlidar_state_type mmlidar_state;





  typedef boost::shared_ptr< ::all_msgs_srvs::systemState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::all_msgs_srvs::systemState_<ContainerAllocator> const> ConstPtr;

}; // struct systemState_

typedef ::all_msgs_srvs::systemState_<std::allocator<void> > systemState;

typedef boost::shared_ptr< ::all_msgs_srvs::systemState > systemStatePtr;
typedef boost::shared_ptr< ::all_msgs_srvs::systemState const> systemStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::all_msgs_srvs::systemState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::all_msgs_srvs::systemState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::all_msgs_srvs::systemState_<ContainerAllocator1> & lhs, const ::all_msgs_srvs::systemState_<ContainerAllocator2> & rhs)
{
  return lhs.device_id == rhs.device_id &&
    lhs.temperature == rhs.temperature &&
    lhs.occ_RAM == rhs.occ_RAM &&
    lhs.occ_CPU == rhs.occ_CPU &&
    lhs.occ_GPU == rhs.occ_GPU &&
    lhs.occ_memory_sda1 == rhs.occ_memory_sda1 &&
    lhs.occ_memory_home == rhs.occ_memory_home &&
    lhs.precess_state == rhs.precess_state &&
    lhs.camera_state == rhs.camera_state &&
    lhs.mmlidar_state == rhs.mmlidar_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::all_msgs_srvs::systemState_<ContainerAllocator1> & lhs, const ::all_msgs_srvs::systemState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace all_msgs_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs_srvs::systemState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs_srvs::systemState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs_srvs::systemState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs_srvs::systemState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs_srvs::systemState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs_srvs::systemState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::all_msgs_srvs::systemState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e6672b93cb0d4c408677cdddcfc6c31";
  }

  static const char* value(const ::all_msgs_srvs::systemState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e6672b93cb0d4c4ULL;
  static const uint64_t static_value2 = 0x08677cdddcfc6c31ULL;
};

template<class ContainerAllocator>
struct DataType< ::all_msgs_srvs::systemState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "all_msgs_srvs/systemState";
  }

  static const char* value(const ::all_msgs_srvs::systemState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::all_msgs_srvs::systemState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 device_id\n"
"float32 temperature\n"
"float32 occ_RAM\n"
"float32 occ_CPU\n"
"float32 occ_GPU\n"
"float32 occ_memory_sda1\n"
"float32 occ_memory_home\n"
"float32 precess_state\n"
"float32 camera_state\n"
"float32 mmlidar_state\n"
"\n"
"\n"
;
  }

  static const char* value(const ::all_msgs_srvs::systemState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::all_msgs_srvs::systemState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.device_id);
      stream.next(m.temperature);
      stream.next(m.occ_RAM);
      stream.next(m.occ_CPU);
      stream.next(m.occ_GPU);
      stream.next(m.occ_memory_sda1);
      stream.next(m.occ_memory_home);
      stream.next(m.precess_state);
      stream.next(m.camera_state);
      stream.next(m.mmlidar_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct systemState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::all_msgs_srvs::systemState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::all_msgs_srvs::systemState_<ContainerAllocator>& v)
  {
    s << indent << "device_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.device_id);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
    s << indent << "occ_RAM: ";
    Printer<float>::stream(s, indent + "  ", v.occ_RAM);
    s << indent << "occ_CPU: ";
    Printer<float>::stream(s, indent + "  ", v.occ_CPU);
    s << indent << "occ_GPU: ";
    Printer<float>::stream(s, indent + "  ", v.occ_GPU);
    s << indent << "occ_memory_sda1: ";
    Printer<float>::stream(s, indent + "  ", v.occ_memory_sda1);
    s << indent << "occ_memory_home: ";
    Printer<float>::stream(s, indent + "  ", v.occ_memory_home);
    s << indent << "precess_state: ";
    Printer<float>::stream(s, indent + "  ", v.precess_state);
    s << indent << "camera_state: ";
    Printer<float>::stream(s, indent + "  ", v.camera_state);
    s << indent << "mmlidar_state: ";
    Printer<float>::stream(s, indent + "  ", v.mmlidar_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALL_MSGS_SRVS_MESSAGE_SYSTEMSTATE_H
