# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from all_msgs_srvs/settings.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class settings(genpy.Message):
  _md5sum = "2c5fd6a4bb0c365ef3a2eff725118bfe"
  _type = "all_msgs_srvs/settings"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time stamp
uint16 frame_id
uint32 type
uint32 which_param
float32[] setdatas


#type:
#lan_info(0)
#statis_info(1)
#Transform_info(2)
#Network_info(3)
#Install_Info(4)


#which_param
#1101:给统计节点设置热参数[A,B,C,车道数,车道1断面数,车道1断面1距离,车道1断面2距离,...,车道n断面数,车道n断面1距离,车道n断面2距离...]
#1102:[周期]
#3001:[设备id]
#1001:车道坐标设置 [车道总数,]


"""
  __slots__ = ['stamp','frame_id','type','which_param','setdatas']
  _slot_types = ['time','uint16','uint32','uint32','float32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,frame_id,type,which_param,setdatas

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(settings, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.frame_id is None:
        self.frame_id = 0
      if self.type is None:
        self.type = 0
      if self.which_param is None:
        self.which_param = 0
      if self.setdatas is None:
        self.setdatas = []
    else:
      self.stamp = genpy.Time()
      self.frame_id = 0
      self.type = 0
      self.which_param = 0
      self.setdatas = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2IH2I().pack(_x.stamp.secs, _x.stamp.nsecs, _x.frame_id, _x.type, _x.which_param))
      length = len(self.setdatas)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.setdatas))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 18
      (_x.stamp.secs, _x.stamp.nsecs, _x.frame_id, _x.type, _x.which_param,) = _get_struct_2IH2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.setdatas = s.unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2IH2I().pack(_x.stamp.secs, _x.stamp.nsecs, _x.frame_id, _x.type, _x.which_param))
      length = len(self.setdatas)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.setdatas.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 18
      (_x.stamp.secs, _x.stamp.nsecs, _x.frame_id, _x.type, _x.which_param,) = _get_struct_2IH2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.setdatas = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2IH2I = None
def _get_struct_2IH2I():
    global _struct_2IH2I
    if _struct_2IH2I is None:
        _struct_2IH2I = struct.Struct("<2IH2I")
    return _struct_2IH2I
