// Generated by gencpp from file all_msgs_srvs/errorMsgs.msg
// DO NOT EDIT!


#ifndef ALL_MSGS_SRVS_MESSAGE_ERRORMSGS_H
#define ALL_MSGS_SRVS_MESSAGE_ERRORMSGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace all_msgs_srvs
{
template <class ContainerAllocator>
struct errorMsgs_
{
  typedef errorMsgs_<ContainerAllocator> Type;

  errorMsgs_()
    : device_id(0)
    , type(0)
    , data()  {
    }
  errorMsgs_(const ContainerAllocator& _alloc)
    : device_id(0)
    , type(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _device_id_type;
  _device_id_type device_id;

   typedef uint32_t _type_type;
  _type_type type;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::all_msgs_srvs::errorMsgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::all_msgs_srvs::errorMsgs_<ContainerAllocator> const> ConstPtr;

}; // struct errorMsgs_

typedef ::all_msgs_srvs::errorMsgs_<std::allocator<void> > errorMsgs;

typedef boost::shared_ptr< ::all_msgs_srvs::errorMsgs > errorMsgsPtr;
typedef boost::shared_ptr< ::all_msgs_srvs::errorMsgs const> errorMsgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::all_msgs_srvs::errorMsgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::all_msgs_srvs::errorMsgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::all_msgs_srvs::errorMsgs_<ContainerAllocator1> & lhs, const ::all_msgs_srvs::errorMsgs_<ContainerAllocator2> & rhs)
{
  return lhs.device_id == rhs.device_id &&
    lhs.type == rhs.type &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::all_msgs_srvs::errorMsgs_<ContainerAllocator1> & lhs, const ::all_msgs_srvs::errorMsgs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace all_msgs_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs_srvs::errorMsgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs_srvs::errorMsgs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs_srvs::errorMsgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs_srvs::errorMsgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs_srvs::errorMsgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs_srvs::errorMsgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::all_msgs_srvs::errorMsgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da293913ab09cf0b6203d2182912db2a";
  }

  static const char* value(const ::all_msgs_srvs::errorMsgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda293913ab09cf0bULL;
  static const uint64_t static_value2 = 0x6203d2182912db2aULL;
};

template<class ContainerAllocator>
struct DataType< ::all_msgs_srvs::errorMsgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "all_msgs_srvs/errorMsgs";
  }

  static const char* value(const ::all_msgs_srvs::errorMsgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::all_msgs_srvs::errorMsgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 device_id\n"
"uint32 type\n"
"float32[] data\n"
"\n"
"#type:0错误信息,1警告消息,2系统消息\n"
"\n"
"\n"
"\n"
;
  }

  static const char* value(const ::all_msgs_srvs::errorMsgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::all_msgs_srvs::errorMsgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.device_id);
      stream.next(m.type);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct errorMsgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::all_msgs_srvs::errorMsgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::all_msgs_srvs::errorMsgs_<ContainerAllocator>& v)
  {
    s << indent << "device_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.device_id);
    s << indent << "type: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.type);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALL_MSGS_SRVS_MESSAGE_ERRORMSGS_H
