// Generated by gencpp from file all_msgs_srvs/settings.msg
// DO NOT EDIT!


#ifndef ALL_MSGS_SRVS_MESSAGE_SETTINGS_H
#define ALL_MSGS_SRVS_MESSAGE_SETTINGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace all_msgs_srvs
{
template <class ContainerAllocator>
struct settings_
{
  typedef settings_<ContainerAllocator> Type;

  settings_()
    : stamp()
    , frame_id(0)
    , type(0)
    , which_param(0)
    , setdatas()  {
    }
  settings_(const ContainerAllocator& _alloc)
    : stamp()
    , frame_id(0)
    , type(0)
    , which_param(0)
    , setdatas(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef uint16_t _frame_id_type;
  _frame_id_type frame_id;

   typedef uint32_t _type_type;
  _type_type type;

   typedef uint32_t _which_param_type;
  _which_param_type which_param;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _setdatas_type;
  _setdatas_type setdatas;





  typedef boost::shared_ptr< ::all_msgs_srvs::settings_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::all_msgs_srvs::settings_<ContainerAllocator> const> ConstPtr;

}; // struct settings_

typedef ::all_msgs_srvs::settings_<std::allocator<void> > settings;

typedef boost::shared_ptr< ::all_msgs_srvs::settings > settingsPtr;
typedef boost::shared_ptr< ::all_msgs_srvs::settings const> settingsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::all_msgs_srvs::settings_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::all_msgs_srvs::settings_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::all_msgs_srvs::settings_<ContainerAllocator1> & lhs, const ::all_msgs_srvs::settings_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.frame_id == rhs.frame_id &&
    lhs.type == rhs.type &&
    lhs.which_param == rhs.which_param &&
    lhs.setdatas == rhs.setdatas;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::all_msgs_srvs::settings_<ContainerAllocator1> & lhs, const ::all_msgs_srvs::settings_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace all_msgs_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs_srvs::settings_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs_srvs::settings_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs_srvs::settings_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs_srvs::settings_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs_srvs::settings_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs_srvs::settings_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::all_msgs_srvs::settings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c5fd6a4bb0c365ef3a2eff725118bfe";
  }

  static const char* value(const ::all_msgs_srvs::settings_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c5fd6a4bb0c365eULL;
  static const uint64_t static_value2 = 0xf3a2eff725118bfeULL;
};

template<class ContainerAllocator>
struct DataType< ::all_msgs_srvs::settings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "all_msgs_srvs/settings";
  }

  static const char* value(const ::all_msgs_srvs::settings_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::all_msgs_srvs::settings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"uint16 frame_id\n"
"uint32 type\n"
"uint32 which_param\n"
"float32[] setdatas\n"
"\n"
"\n"
"#type:\n"
"#lan_info(0)\n"
"#statis_info(1)\n"
"#Transform_info(2)\n"
"#Network_info(3)\n"
"#Install_Info(4)\n"
"\n"
"\n"
"#which_param\n"
"#1101:给统计节点设置热参数[A,B,C,车道数,车道1断面数,车道1断面1距离,车道1断面2距离,...,车道n断面数,车道n断面1距离,车道n断面2距离...]\n"
"#1102:[周期]\n"
"#3001:[设备id]\n"
"#1001:车道坐标设置 [车道总数,]\n"
"\n"
"\n"
;
  }

  static const char* value(const ::all_msgs_srvs::settings_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::all_msgs_srvs::settings_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.frame_id);
      stream.next(m.type);
      stream.next(m.which_param);
      stream.next(m.setdatas);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct settings_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::all_msgs_srvs::settings_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::all_msgs_srvs::settings_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "frame_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.frame_id);
    s << indent << "type: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.type);
    s << indent << "which_param: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.which_param);
    s << indent << "setdatas[]" << std::endl;
    for (size_t i = 0; i < v.setdatas.size(); ++i)
    {
      s << indent << "  setdatas[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.setdatas[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALL_MSGS_SRVS_MESSAGE_SETTINGS_H
