// Generated by gencpp from file all_msgs_srvs/settingcallbackResponse.msg
// DO NOT EDIT!


#ifndef ALL_MSGS_SRVS_MESSAGE_SETTINGCALLBACKRESPONSE_H
#define ALL_MSGS_SRVS_MESSAGE_SETTINGCALLBACKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace all_msgs_srvs
{
template <class ContainerAllocator>
struct settingcallbackResponse_
{
  typedef settingcallbackResponse_<ContainerAllocator> Type;

  settingcallbackResponse_()
    : setdatas()  {
    }
  settingcallbackResponse_(const ContainerAllocator& _alloc)
    : setdatas(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _setdatas_type;
  _setdatas_type setdatas;





  typedef boost::shared_ptr< ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator> const> ConstPtr;

}; // struct settingcallbackResponse_

typedef ::all_msgs_srvs::settingcallbackResponse_<std::allocator<void> > settingcallbackResponse;

typedef boost::shared_ptr< ::all_msgs_srvs::settingcallbackResponse > settingcallbackResponsePtr;
typedef boost::shared_ptr< ::all_msgs_srvs::settingcallbackResponse const> settingcallbackResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator1> & lhs, const ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator2> & rhs)
{
  return lhs.setdatas == rhs.setdatas;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator1> & lhs, const ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace all_msgs_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c05e33076ac043125f4405803716ae5";
  }

  static const char* value(const ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c05e33076ac0431ULL;
  static const uint64_t static_value2 = 0x25f4405803716ae5ULL;
};

template<class ContainerAllocator>
struct DataType< ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "all_msgs_srvs/settingcallbackResponse";
  }

  static const char* value(const ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] setdatas\n"
"\n"
"\n"
;
  }

  static const char* value(const ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.setdatas);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct settingcallbackResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::all_msgs_srvs::settingcallbackResponse_<ContainerAllocator>& v)
  {
    s << indent << "setdatas[]" << std::endl;
    for (size_t i = 0; i < v.setdatas.size(); ++i)
    {
      s << indent << "  setdatas[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.setdatas[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALL_MSGS_SRVS_MESSAGE_SETTINGCALLBACKRESPONSE_H
