// Generated by gencpp from file all_msgs_srvs/systemlog.msg
// DO NOT EDIT!


#ifndef ALL_MSGS_SRVS_MESSAGE_SYSTEMLOG_H
#define ALL_MSGS_SRVS_MESSAGE_SYSTEMLOG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace all_msgs_srvs
{
template <class ContainerAllocator>
struct systemlog_
{
  typedef systemlog_<ContainerAllocator> Type;

  systemlog_()
    : device_id(0)
    , node_id()
    , type(0)
    , describe()
    , data()  {
    }
  systemlog_(const ContainerAllocator& _alloc)
    : device_id(0)
    , node_id(_alloc)
    , type(0)
    , describe(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _device_id_type;
  _device_id_type device_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _node_id_type;
  _node_id_type node_id;

   typedef uint32_t _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _describe_type;
  _describe_type describe;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::all_msgs_srvs::systemlog_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::all_msgs_srvs::systemlog_<ContainerAllocator> const> ConstPtr;

}; // struct systemlog_

typedef ::all_msgs_srvs::systemlog_<std::allocator<void> > systemlog;

typedef boost::shared_ptr< ::all_msgs_srvs::systemlog > systemlogPtr;
typedef boost::shared_ptr< ::all_msgs_srvs::systemlog const> systemlogConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::all_msgs_srvs::systemlog_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::all_msgs_srvs::systemlog_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::all_msgs_srvs::systemlog_<ContainerAllocator1> & lhs, const ::all_msgs_srvs::systemlog_<ContainerAllocator2> & rhs)
{
  return lhs.device_id == rhs.device_id &&
    lhs.node_id == rhs.node_id &&
    lhs.type == rhs.type &&
    lhs.describe == rhs.describe &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::all_msgs_srvs::systemlog_<ContainerAllocator1> & lhs, const ::all_msgs_srvs::systemlog_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace all_msgs_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs_srvs::systemlog_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs_srvs::systemlog_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs_srvs::systemlog_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs_srvs::systemlog_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs_srvs::systemlog_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs_srvs::systemlog_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::all_msgs_srvs::systemlog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe73fa608b885c27025369005afbf02b";
  }

  static const char* value(const ::all_msgs_srvs::systemlog_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe73fa608b885c27ULL;
  static const uint64_t static_value2 = 0x025369005afbf02bULL;
};

template<class ContainerAllocator>
struct DataType< ::all_msgs_srvs::systemlog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "all_msgs_srvs/systemlog";
  }

  static const char* value(const ::all_msgs_srvs::systemlog_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::all_msgs_srvs::systemlog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 device_id\n"
"string node_id\n"
"uint32 type\n"
"string describe\n"
"float32[] data\n"
"\n"
"\n"
"#数据意义\n"
"#device_id:表示设备id\n"
"#node_id:表示哪个节点\n"
"#type:表示什么类型的标识,1(warring),2(info),其他(debug),10(error致命错误),11(error一般错误)\n"
"#describe:问题表述,操作表述\n"
"#data:操作的数据\n"
"\n"
"\n"
;
  }

  static const char* value(const ::all_msgs_srvs::systemlog_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::all_msgs_srvs::systemlog_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.device_id);
      stream.next(m.node_id);
      stream.next(m.type);
      stream.next(m.describe);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct systemlog_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::all_msgs_srvs::systemlog_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::all_msgs_srvs::systemlog_<ContainerAllocator>& v)
  {
    s << indent << "device_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.device_id);
    s << indent << "node_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.node_id);
    s << indent << "type: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.type);
    s << indent << "describe: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.describe);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALL_MSGS_SRVS_MESSAGE_SYSTEMLOG_H
