// Generated by gencpp from file all_msgs_srvs/vehicalmsgs.msg
// DO NOT EDIT!


#ifndef ALL_MSGS_SRVS_MESSAGE_VEHICALMSGS_H
#define ALL_MSGS_SRVS_MESSAGE_VEHICALMSGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace all_msgs_srvs
{
template <class ContainerAllocator>
struct vehicalmsgs_
{
  typedef vehicalmsgs_<ContainerAllocator> Type;

  vehicalmsgs_()
    : stamp()
    , frame_id(0)
    , vehicaldatas()  {
    }
  vehicalmsgs_(const ContainerAllocator& _alloc)
    : stamp()
    , frame_id(0)
    , vehicaldatas(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef uint16_t _frame_id_type;
  _frame_id_type frame_id;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _vehicaldatas_type;
  _vehicaldatas_type vehicaldatas;





  typedef boost::shared_ptr< ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator> const> ConstPtr;

}; // struct vehicalmsgs_

typedef ::all_msgs_srvs::vehicalmsgs_<std::allocator<void> > vehicalmsgs;

typedef boost::shared_ptr< ::all_msgs_srvs::vehicalmsgs > vehicalmsgsPtr;
typedef boost::shared_ptr< ::all_msgs_srvs::vehicalmsgs const> vehicalmsgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator1> & lhs, const ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.frame_id == rhs.frame_id &&
    lhs.vehicaldatas == rhs.vehicaldatas;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator1> & lhs, const ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace all_msgs_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3744cc7a9e5f2c7d66d5bd9cb6fa612d";
  }

  static const char* value(const ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3744cc7a9e5f2c7dULL;
  static const uint64_t static_value2 = 0x66d5bd9cb6fa612dULL;
};

template<class ContainerAllocator>
struct DataType< ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "all_msgs_srvs/vehicalmsgs";
  }

  static const char* value(const ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"uint16 frame_id\n"
"float32[] vehicaldatas\n"
"\n"
"#[id,sort,lan,v,x,y]\n"
;
  }

  static const char* value(const ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.frame_id);
      stream.next(m.vehicaldatas);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vehicalmsgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::all_msgs_srvs::vehicalmsgs_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "frame_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.frame_id);
    s << indent << "vehicaldatas[]" << std::endl;
    for (size_t i = 0; i < v.vehicaldatas.size(); ++i)
    {
      s << indent << "  vehicaldatas[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.vehicaldatas[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALL_MSGS_SRVS_MESSAGE_VEHICALMSGS_H
