# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from all_msgs_srvs/systemState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class systemState(genpy.Message):
  _md5sum = "8e6672b93cb0d4c408677cdddcfc6c31"
  _type = "all_msgs_srvs/systemState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32 device_id
float32 temperature
float32 occ_RAM
float32 occ_CPU
float32 occ_GPU
float32 occ_memory_sda1
float32 occ_memory_home
float32 precess_state
float32 camera_state
float32 mmlidar_state


"""
  __slots__ = ['device_id','temperature','occ_RAM','occ_CPU','occ_GPU','occ_memory_sda1','occ_memory_home','precess_state','camera_state','mmlidar_state']
  _slot_types = ['uint32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       device_id,temperature,occ_RAM,occ_CPU,occ_GPU,occ_memory_sda1,occ_memory_home,precess_state,camera_state,mmlidar_state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(systemState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.device_id is None:
        self.device_id = 0
      if self.temperature is None:
        self.temperature = 0.
      if self.occ_RAM is None:
        self.occ_RAM = 0.
      if self.occ_CPU is None:
        self.occ_CPU = 0.
      if self.occ_GPU is None:
        self.occ_GPU = 0.
      if self.occ_memory_sda1 is None:
        self.occ_memory_sda1 = 0.
      if self.occ_memory_home is None:
        self.occ_memory_home = 0.
      if self.precess_state is None:
        self.precess_state = 0.
      if self.camera_state is None:
        self.camera_state = 0.
      if self.mmlidar_state is None:
        self.mmlidar_state = 0.
    else:
      self.device_id = 0
      self.temperature = 0.
      self.occ_RAM = 0.
      self.occ_CPU = 0.
      self.occ_GPU = 0.
      self.occ_memory_sda1 = 0.
      self.occ_memory_home = 0.
      self.precess_state = 0.
      self.camera_state = 0.
      self.mmlidar_state = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_I9f().pack(_x.device_id, _x.temperature, _x.occ_RAM, _x.occ_CPU, _x.occ_GPU, _x.occ_memory_sda1, _x.occ_memory_home, _x.precess_state, _x.camera_state, _x.mmlidar_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.device_id, _x.temperature, _x.occ_RAM, _x.occ_CPU, _x.occ_GPU, _x.occ_memory_sda1, _x.occ_memory_home, _x.precess_state, _x.camera_state, _x.mmlidar_state,) = _get_struct_I9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_I9f().pack(_x.device_id, _x.temperature, _x.occ_RAM, _x.occ_CPU, _x.occ_GPU, _x.occ_memory_sda1, _x.occ_memory_home, _x.precess_state, _x.camera_state, _x.mmlidar_state))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.device_id, _x.temperature, _x.occ_RAM, _x.occ_CPU, _x.occ_GPU, _x.occ_memory_sda1, _x.occ_memory_home, _x.precess_state, _x.camera_state, _x.mmlidar_state,) = _get_struct_I9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_I9f = None
def _get_struct_I9f():
    global _struct_I9f
    if _struct_I9f is None:
        _struct_I9f = struct.Struct("<I9f")
    return _struct_I9f
